### ISSUE TITLE
Error From Webpack when using DIJS

### ISSUE THREAD

**Issue by jaredmahan** [avighier/simple-dijs#78]
Can we get this fixed where it does not throw a warning when used?

I am requiring it as follows:
`import Di from 'simple-dijs';`

Error from Webpack:
`WARNING in ./~/simple-dijs/dist/di.js
Critical dependencies:
26:88-96 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/simple-dijs/dist/di.js 26:88-96`

**Comment by avighier** [comment]
Hi Jaredmahan,

I don't know Webpack to understand correctly the problem. What I understand is that Webpack doesn't like the file is not the source, but a "browserify bundle".

Is it a only a warning or does it block your process ?

What I can do is publish the source file and see to think about "main" in package.json.

**Comment by avighier** [comment]
As I have not answer, I guess there is not problem.
